module.exports = {
  wrapper: {
    margin: '0 auto',
    position: 'relative',
    width: ['100%', '100%', '80%'],
    clear: 'both',
  },
  buttonWrapper: {
    display: 'none',
  },
  buttonWrapperOwner:  {
    display: 'inline-block',
    marginTop: '1rem',
    verticalAlign: 'top',
    clear: 'both',
  },
  innerWrapper: {
    clear: 'both',
    border: '1px solid',
    borderColor: 'gray.0',
    display: 'inline-block',
    minWidth: '100%',
    pt: '1rem',
    px: '1rem',
    pb: '1rem',
    margin: '1rem auto',
    verticalAlign: 'top',
    whiteSpace: 'pre',
    width: ['100%', '100%', '80%'],
  },
  innerWrapperOwner: {
    clear: 'both',
    border: '1px solid',
    borderColor: 'gray.2',
    display: 'inline-block',
    minWidth: 'calc(100% - 60px)',
    pt: '1rem',
    px: '1rem',
    pb: '1rem',
    margin: '1rem auto',
    verticalAlign: 'top',
    whiteSpace: 'pre',
    width: ['100%', '100%', 'calc(80% - 60px)'],
  },
}
